export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_FILTERED_PRODUCTS_LIST = 'GET_FILTERED_PRODUCTS_LIST';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const SET_LOADING = 'SET_LOADING';
